import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowRight, Check, Eye, Loader2, RefreshCw, Sparkles, Wand2, X, Youtube, Zap } from 'lucide-react';
import type { Studio } from '../useStudio';
import type { Idea, Source } from '../types';
import { formatById } from '../formats';
import { buildIdeasPrompt, describeError, generate, parseIdeas, recommendIdeas } from '../claude';
import { formatViews } from '../youtube';
import { ManualRunModal } from './ManualRunModal';
import { Btn, inputCls, labelCls } from './ui';
import { timeAgo } from '../util';

const MAX_CATALOG = 150;
const STALE_MS = 6 * 60 * 60 * 1000;

type MakeState = { state: 'making' | 'done' | 'error'; message?: string };

export function AutoPanel({ studio, onOpenPiece }: { studio: Studio; onOpenPiece: (pieceId: string, autoRun?: boolean) => void }) {
  const { project, settings } = studio;
  const [channelInput, setChannelInput] = useState(project?.channel?.input ?? '');
  const [syncing, setSyncing] = useState(false);
  const [syncError, setSyncError] = useState('');
  const [count, setCount] = useState(8);
  const [thinking, setThinking] = useState(false);
  const [ideasError, setIdeasError] = useState('');
  const [manual, setManual] = useState<{ error?: string } | null>(null);
  const [making, setMaking] = useState<Record<string, MakeState>>({});
  const abortRef = useRef<AbortController | null>(null);
  const hasKey = !!settings.apiKey;

  useEffect(() => setChannelInput(project?.channel?.input ?? ''), [project?.id]); // eslint-disable-line react-hooks/exhaustive-deps

  const videos = useMemo(() => {
    const channelId = project?.channel?.channelId;
    return studio.sources
      .filter((s) => s.kind === 'youtube' && s.youtube && (!channelId || s.youtube.channelId === channelId) && s.youtube.channelId)
      .sort((a, b) => (b.youtube!.publishedAt ?? '').localeCompare(a.youtube!.publishedAt ?? ''));
  }, [studio.sources, project?.channel?.channelId]);
  const catalog = videos.slice(0, MAX_CATALOG);
  const byVideoId = useMemo(() => new Map(videos.map((v) => [v.youtube!.videoId, v])), [videos]);
  const topVideos = useMemo(() => [...videos].sort((a, b) => (b.youtube!.views ?? 0) - (a.youtube!.views ?? 0)).slice(0, 8), [videos]);
  const withTranscripts = videos.filter((v) => v.text?.trim()).length;

  const sync = async (input = channelInput) => {
    if (!input.trim()) return;
    setSyncing(true);
    setSyncError('');
    try {
      await studio.syncChannel(input.trim());
    } catch (e) {
      setSyncError(e instanceof Error ? e.message : String(e));
    } finally {
      setSyncing(false);
    }
  };

  // Keep the catalog fresh: re-read the channel when the panel opens and the last sync is stale.
  useEffect(() => {
    const ch = project?.channel;
    if (ch?.input && (!ch.lastSyncedAt || Date.now() - ch.lastSyncedAt > STALE_MS)) sync(ch.input);
  }, [project?.id]); // eslint-disable-line react-hooks/exhaustive-deps

  if (!project) return null;
  const ideas = project.ideas ?? [];
  const ideasRequest = { project, videos: catalog, goal: project.ideasGoal ?? '', count };

  const saveIdeas = (list: Idea[]) =>
    studio.updateProject((p) => ({ ideas: [...list, ...(p.ideas ?? []).filter((i) => i.pieceId)], ideasGeneratedAt: Date.now() }));

  const recommend = async () => {
    setIdeasError('');
    if (!hasKey) return setManual({});
    const controller = new AbortController();
    abortRef.current = controller;
    setThinking(true);
    try {
      await saveIdeas(await recommendIdeas(settings, ideasRequest, controller.signal));
    } catch (e) {
      setIdeasError(describeError(e));
    } finally {
      setThinking(false);
    }
  };

  /** One click: create the piece, then generate it here (with a key) or hand off to the editor's Claude.ai flow. */
  const make = async (idea: Idea) => {
    const piece = await studio.pieceFromIdea(idea);
    if (!piece) return;
    if (!hasKey) return onOpenPiece(piece.id, true);
    setMaking((m) => ({ ...m, [idea.id]: { state: 'making' } }));
    try {
      const { text, model } = await generate({
        settings,
        project,
        piece,
        sources: studio.sourceMap,
        mode: 'generate',
        variations: 1,
        onText: () => {},
        signal: new AbortController().signal,
      });
      studio.updatePiece(piece.id, { body: text });
      await studio.snapshot(piece.id, text, 'generate', 'Generated by Auto', {
        model,
        brief: piece.brief,
        sourceTitles: piece.sources.map((r) => studio.sourceMap.get(r.sourceId)?.title ?? ''),
      });
      setMaking((m) => ({ ...m, [idea.id]: { state: 'done' } }));
    } catch (e) {
      setMaking((m) => ({ ...m, [idea.id]: { state: 'error', message: describeError(e) } }));
    }
  };

  const makeAll = async () => {
    for (const idea of ideas.filter((i) => !i.pieceId)) await make(idea);
  };

  const dismiss = (idea: Idea) => studio.updateProject((p) => ({ ideas: (p.ideas ?? []).filter((i) => i.id !== idea.id) }));

  return (
    <section className="flex h-full min-w-0 flex-1 flex-col overflow-y-auto bg-white">
      <div className="border-b border-slate-100 bg-gradient-to-br from-indigo-50 via-white to-violet-50 px-6 py-5">
        <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-indigo-600">
          <Zap className="h-3.5 w-3.5" /> Auto
        </div>
        <h2 className="mt-1 text-xl font-semibold text-slate-900">Ideas from your channel, made in one click</h2>
        <p className="mt-1 max-w-2xl text-sm text-slate-600">
          Claude reads your channel's videos and your goals, recommends promos, explainers, recaps and more, then drafts any of them with the right videos already attached.
        </p>
      </div>

      <div className="grid gap-6 px-6 py-5 xl:grid-cols-[minmax(0,420px)_minmax(0,1fr)]">
        {/* Channel + goal */}
        <div className="space-y-5">
          <div className="rounded-2xl border border-slate-200 p-4">
            <label className={labelCls}>YouTube channel</label>
            <div className="flex gap-2">
              <div className="relative min-w-0 flex-1">
                <Youtube className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-rose-500" />
                <input
                  className={`${inputCls} pl-9`}
                  value={channelInput}
                  onChange={(e) => setChannelInput(e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && sync()}
                  placeholder="@BattleBots or channel URL"
                />
              </div>
              <Btn onClick={() => sync()} disabled={syncing || !channelInput.trim()}>
                {syncing ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />} Sync
              </Btn>
            </div>
            {syncError && <p className="mt-2 rounded-lg bg-rose-50 px-3 py-2 text-xs text-rose-700">{syncError}</p>}
            {project.channel?.lastSyncedAt && (
              <p className="mt-2 text-xs text-slate-500">
                <span className="font-medium text-slate-700">{project.channel.title}</span> · {videos.length} videos in your library · {withTranscripts} with transcripts ·
                synced {timeAgo(project.channel.lastSyncedAt)}
              </p>
            )}
            <p className="mt-2 text-[11px] leading-relaxed text-slate-500">
              {settings.youtubeApiKey || project.channel?.via === 'api'
                ? 'Reading your full upload history with views and durations via the YouTube API.'
                : "Reading your latest 15 uploads. For your full history, add a YOUTUBE_API_KEY environment variable to the Netlify site (or a key in Settings). Videos build up in your library with every sync."}{' '}
              Transcripts let Claude cite exact moments: click a video in Sources to paste one.
            </p>

            {topVideos.length > 0 && (
              <div className="mt-3">
                <div className="mb-1.5 text-[11px] font-medium uppercase tracking-wide text-slate-400">Top by views</div>
                <div className="grid grid-cols-4 gap-1.5">
                  {topVideos.map((v) => (
                    <a key={v.id} href={v.url} target="_blank" rel="noreferrer" title={`${v.title} · ${formatViews(v.youtube?.views)}`} className="group relative overflow-hidden rounded-lg">
                      <img src={v.youtube!.thumbnail} alt="" className="aspect-video w-full object-cover transition group-hover:scale-105" />
                      <span className="absolute bottom-0.5 right-0.5 rounded bg-black/70 px-1 text-[9px] font-medium text-white">{formatViews(v.youtube?.views).replace(' views', '')}</span>
                    </a>
                  ))}
                </div>
              </div>
            )}
          </div>

          <div className="rounded-2xl border border-slate-200 p-4">
            <label className={labelCls}>What's going on / what do you want?</label>
            <textarea
              className={`${inputCls} h-32`}
              value={project.ideasGoal ?? ''}
              onChange={(e) => studio.updateProject({ ideasGoal: e.target.value })}
              placeholder="e.g. We're halfway through the Pro League season with 20 full episodes plus compilation content. Drive FOMO so people binge-watch before the second half. Lots of action, cliffhangers."
            />
            <p className="mt-1 text-[11px] text-slate-500">This is also added to the key facts of every piece made from an idea.</p>
            <div className="mt-3 flex items-center gap-2">
              <select className="rounded-lg border border-slate-200 px-2 py-2 text-sm" value={count} onChange={(e) => setCount(Number(e.target.value))}>
                {[4, 6, 8, 10, 12].map((n) => (
                  <option key={n} value={n}>{n} ideas</option>
                ))}
              </select>
              <Btn variant="primary" className="flex-1" onClick={recommend} disabled={thinking || catalog.length === 0}>
                {thinking ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
                {thinking ? 'Studying your channel…' : hasKey ? 'Recommend content' : 'Recommend with Claude.ai'}
              </Btn>
            </div>
            {catalog.length === 0 && <p className="mt-2 text-xs text-amber-700">Sync your channel first.</p>}
            {ideasError && <p className="mt-2 rounded-lg bg-rose-50 px-3 py-2 text-xs text-rose-700">{ideasError}</p>}
          </div>
        </div>

        {/* Ideas */}
        <div>
          <div className="mb-3 flex items-center justify-between gap-2">
            <div>
              <h3 className="text-sm font-semibold text-slate-900">Recommended</h3>
              <p className="text-xs text-slate-500">{ideas.length ? `${ideas.length} ideas${project.ideasGeneratedAt ? ` · ${timeAgo(project.ideasGeneratedAt)}` : ''}` : 'Ideas will appear here.'}</p>
            </div>
            {hasKey && ideas.some((i) => !i.pieceId) && (
              <Btn size="sm" onClick={makeAll} disabled={Object.values(making).some((m) => m.state === 'making')}>
                <Wand2 className="h-3.5 w-3.5" /> Make all
              </Btn>
            )}
          </div>

          {ideas.length === 0 && (
            <div className="rounded-2xl border-2 border-dashed border-slate-200 p-10 text-center">
              <Sparkles className="mx-auto h-7 w-7 text-slate-300" />
              <p className="mx-auto mt-2 max-w-sm text-sm text-slate-500">Sync your channel, say what's going on, and press Recommend. You'll get ready-to-make ideas with the right videos attached.</p>
            </div>
          )}

          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2">
            {ideas.map((idea) => {
              const m = making[idea.id];
              const vids = idea.videoIds.map((id) => byVideoId.get(id)).filter((v): v is Source => !!v);
              return (
                <article key={idea.id} className="flex flex-col rounded-2xl border border-slate-200 bg-white p-4 shadow-sm transition hover:shadow-md">
                  <div className="flex items-start justify-between gap-2">
                    <span className="rounded-full bg-indigo-50 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-indigo-700">{formatById(idea.format).label}</span>
                    <button onClick={() => dismiss(idea)} title="Dismiss" className="rounded p-1 text-slate-300 hover:bg-slate-100 hover:text-slate-600">
                      <X className="h-3.5 w-3.5" />
                    </button>
                  </div>
                  <h4 className="mt-2 font-semibold leading-snug text-slate-900">{idea.title}</h4>
                  {idea.why && <p className="mt-1 text-xs leading-relaxed text-emerald-700">{idea.why}</p>}
                  <p className="mt-2 line-clamp-4 text-xs leading-relaxed text-slate-600">{idea.brief}</p>
                  {vids.length > 0 && (
                    <div className="mt-3 flex items-center gap-1">
                      {vids.slice(0, 5).map((v) => (
                        <img key={v.id} src={v.youtube!.thumbnail} alt={v.title} title={v.title} className="h-8 w-14 rounded object-cover ring-1 ring-slate-200" />
                      ))}
                      {vids.length > 5 && <span className="ml-1 text-[11px] text-slate-500">+{vids.length - 5}</span>}
                    </div>
                  )}
                  {m?.state === 'error' && <p className="mt-2 rounded-lg bg-rose-50 px-2 py-1.5 text-[11px] text-rose-700">{m.message}</p>}
                  <div className="mt-auto flex items-center gap-2 pt-4">
                    {idea.pieceId ? (
                      <>
                        {m?.state === 'making' ? (
                          <span className="inline-flex items-center gap-1.5 text-xs text-indigo-700">
                            <Loader2 className="h-3.5 w-3.5 animate-spin" /> Making…
                          </span>
                        ) : (
                          <span className="inline-flex items-center gap-1 text-xs font-medium text-emerald-700">
                            <Check className="h-3.5 w-3.5" /> Made
                          </span>
                        )}
                        <Btn size="sm" className="ml-auto" onClick={() => onOpenPiece(idea.pieceId!)}>
                          <Eye className="h-3.5 w-3.5" /> Open
                        </Btn>
                      </>
                    ) : (
                      <Btn size="sm" variant="primary" className="ml-auto" onClick={() => make(idea)}>
                        Make it <ArrowRight className="h-3.5 w-3.5" />
                      </Btn>
                    )}
                  </div>
                </article>
              );
            })}
          </div>
        </div>
      </div>

      {manual && (
        <ManualRunModal
          {...{ prompt: buildIdeasPrompt(ideasRequest), attachments: [] }}
          title="Recommend content with Claude.ai"
          hint="Paste Claude's whole reply (it's JSON). The ideas appear as cards you can make with one click."
          error={manual.error}
          onClose={() => setManual(null)}
          onAccept={(reply) => {
            try {
              saveIdeas(parseIdeas(reply, new Set(catalog.map((v) => v.youtube!.videoId))));
              setManual(null);
            } catch (e) {
              setManual({ error: e instanceof Error ? e.message : String(e) });
            }
          }}
        />
      )}
    </section>
  );
}
